    const translations = {
        th: {
            nav_system: "ระบบทำงานอย่างไร",
            nav_services: "บริการในระบบ",
            nav_ecosystem: "Ecosystem",
            nav_partner: "สำหรับพันธมิตร",
            cta_partner_header: "สมัครเป็นพันธมิตร",
            hero_headline: 'โครงสร้างพื้นฐาน<br>ที่เชื่อมโรงพยาบาล โรงแรม และการเดินทาง<br><span class="text-emerald-600">ไว้ในระบบเดียว</span>',
            hero_body: "WOS ไม่ใช่เว็บขายแพ็กเกจพักฟื้น แต่เป็นระบบประสานงานที่เชื่อมคลินิก โรงพยาบาล เครือข่ายโรงแรม รถรับส่ง และโภชนาการ ให้ทำงานร่วมกันเป็นเส้นทางเดียวสำหรับผู้ป่วยข้ามพรมแดนไทย-ลาว",
            cta_partner: "สมัครเป็นพันธมิตรระบบ",
            cta_investor: "ดู Pitch Deck สำหรับนักลงทุน",
            flow_clinic: "คลินิก",
            flow_wos: "Operating System",
            flow_hotel: "โรงแรม",
            flow_transport: "การขนส่ง",
            flow_nutrition: "โภชนาการ",
            flow_journey: "Journey Manager",
            pilot_badge: "โครงการนำร่อง — อุดรธานี",
            stat_hotels_label: "โรงแรมพันธมิตร",
            stat_clinics_label: "คลินิกพันธมิตร",
            stat_nights_label: "คืนพักฟื้นที่ประสานงาน",
            stat_satisfaction_label: "ความพึงพอใจของผู้เข้าพัก",
            system_title: "ระบบทำงานอย่างไร",
            system_sub: "WOS เป็นตัวกลางที่ประสานงานทุกฝ่ายให้ทำงานร่วมกันโดยอัตโนมัติ",
            step1_title: "Clinic ส่งเคส",
            step1_desc: "โรงพยาบาล/คลินิกวางแผนการรักษา แล้วส่งข้อมูลเคสเข้าระบบ WOS",
            step2_title: "WOS ประมวลผล",
            step2_desc: "ระบบจับคู่ที่พัก รถรับส่ง และอาหารที่เหมาะกับประเภทการรักษา",
            step3_title: "Journey Manager",
            step3_desc: "เจ้าหน้าที่ประสานงานติดตามเคสตลอดเส้นทาง ตั้งแต่รับจนถึงส่งกลับ",
            step4_title: "Partner Hotel",
            step4_desc: "โรงแรมพันธมิตรรับผู้ป่วยตามมาตรฐานการดูแลที่ตกลงไว้ล่วงหน้า",
            step5_title: "Recovery",
            step5_desc: "ผู้ป่วยพักฟื้นอย่างปลอดภัย พร้อมนัดติดตามผลกับคลินิกต้นทาง",
            services_title: "บริการในระบบ",
            services_sub: "โมดูลหลักที่ WOS ประสานงานให้อัตโนมัติสำหรับพันธมิตรทุกฝ่าย",
            svc1_title: "Hospital Services",
            svc1_desc: "รับส่งข้อมูลเคสจากคลินิก/โรงพยาบาล และติดตามสถานะการรักษาแบบเรียลไทม์",
            svc2_title: "Hotel Network",
            svc2_desc: "เครือข่ายโรงแรมที่ผ่านมาตรฐานการดูแลผู้ป่วยพักฟื้น พร้อมระบบจองห้องอัตโนมัติ",
            svc3_title: "Transportation",
            svc3_desc: "รถรับส่ง VIP จากสนามบิน/ด่านพรมแดน ตรงสู่คลินิกและที่พัก",
            svc4_title: "Wellness Nutrition",
            svc4_desc: "เมนูเฉพาะบุคคลตามประเภทการรักษา จัดส่งตรงเวลาโดยพันธมิตรครัว",
            ecosystem_title: "WOS เชื่อมทุกภาคส่วนของ Healthcare Hospitality",
            eco_hospital: "โรงพยาบาล",
            eco_hotel: "โรงแรม",
            eco_wellness: "สุขภาพองค์รวม",
            eco_insurance: "ประกันภัย",
            eco_travel: "การเดินทาง",
            ecosystem_cta: "สมัครเป็นพันธมิตรร่วมระบบ →",
            form_title: "แบบฟอร์มประสานงานสำหรับคลินิกและพันธมิตร",
            form_sub: "กรอกข้อมูลเคสเพื่อส่งเข้าระบบ WOS หรือสมัครเป็นพันธมิตรโรงแรม/คลินิก/นักลงทุน",
            investor_line: "นักลงทุน —",
            investor_link: "ดู Pitch Deck ฉบับเต็ม",
            footer_tagline: "Healthcare Hospitality Operating System เชื่อมโรงพยาบาล โรงแรม และการเดินทาง ไว้ในระบบเดียว",
            footer_partner_heading: "Become Partner",
            footer_for_hospital: "สำหรับโรงพยาบาล",
            footer_for_hotel: "สำหรับโรงแรม",
            footer_for_investor: "สำหรับนักลงทุน",
            footer_career: "ร่วมงานกับเรา",
            footer_system_heading: "ระบบ",
            footer_contact_heading: "ติดต่อ",
            footer_phone: "085-590-7666",
            footer_company_line: "หจก. รอยัล บริตจ์ 99 · เลขที่ 211 หมู่ 3 ถ.มิตรภาพ ต.บ้านจั่น อ.เมือง อุดรธานี 41000 · ทะเบียนนิติบุคคล: 0413568000586 · โทร: 085-590-7666",
            footer_copyright: "© 2026 WOS Platform — Royal Bridge 99 Limited Partnership. All rights reserved."
        },
        lo: {
            nav_system: "ລະບົບເຮັດວຽກແນວໃດ",
            nav_services: "ບໍລິການໃນລະບົບ",
            nav_ecosystem: "Ecosystem",
            nav_partner: "ສຳລັບຄູ່ຮ່ວມທຸລະກິດ",
            cta_partner_header: "ສະໝັກເປັນຄູ່ຮ່ວມທຸລະກິດ",
            hero_headline: 'ພື້ນຖານໂຄງລ່າງ<br>ທີ່ເຊື່ອມໂຮງໝໍ ໂຮງແຮມ ແລະ ການເດີນທາງ<br><span class="text-emerald-600">ເຂົ້າໃນລະບົບດຽວ</span>',
            hero_body: "WOS ບໍ່ແມ່ນເວັບຂາຍແພັກເກັດພັກຟື້ນ ແຕ່ເປັນລະບົບປະສານງານທີ່ເຊື່ອມຄລີນິກ ໂຮງໝໍ ເຄືອຂ່າຍໂຮງແຮມ ລົດຮັບສົ່ງ ແລະ ໂພຊະນາການ ໃຫ້ເຮັດວຽກຮ່ວມກັນເປັນເສັ້ນທາງດຽວສຳລັບຄົນເຈັບຂ້າມຊາຍແດນໄທ-ລາວ",
            cta_partner: "ສະໝັກເປັນຄູ່ຮ່ວມລະບົບ",
            cta_investor: "ເບິ່ງ Pitch Deck ສຳລັບນັກລົງທຶນ",
            flow_clinic: "ຄລີນິກ",
            flow_wos: "Operating System",
            flow_hotel: "ໂຮງແຮມ",
            flow_transport: "ການຂົນສົ່ງ",
            flow_nutrition: "ໂພຊະນາການ",
            flow_journey: "Journey Manager",
            pilot_badge: "ໂຄງການນຳຮ່ອງ — ອຸດອນທານີ",
            stat_hotels_label: "ໂຮງແຮມຄູ່ຮ່ວມທຸລະກິດ",
            stat_clinics_label: "ຄລີນິກຄູ່ຮ່ວມທຸລະກິດ",
            stat_nights_label: "ຄືນພັກຟື້ນທີ່ປະສານງານ",
            stat_satisfaction_label: "ຄວາມພໍໃຈຂອງແຂກ",
            system_title: "ລະບົບເຮັດວຽກແນວໃດ",
            system_sub: "WOS ເປັນຕົວກາງທີ່ປະສານງານທຸກຝ່າຍໃຫ້ເຮັດວຽກຮ່ວມກັນໂດຍອັດຕະໂນມັດ",
            step1_title: "ຄລີນິກສົ່ງເຄສ",
            step1_desc: "ໂຮງໝໍ/ຄລີນິກວາງແຜນການປິ່ນປົວ ແລ້ວສົ່ງຂໍ້ມູນເຄສເຂົ້າລະບົບ WOS",
            step2_title: "WOS ປະມວນຜົນ",
            step2_desc: "ລະບົບຈັບຄູ່ບ່ອນພັກ ລົດຮັບສົ່ງ ແລະ ອາຫານທີ່ເໝາະສົມກັບປະເພດການປິ່ນປົວ",
            step3_title: "Journey Manager",
            step3_desc: "ພະນັກງານປະສານງານຕິດຕາມເຄສຕະຫຼອດເສັ້ນທາງ ຕັ້ງແຕ່ຮັບຈົນເຖິງສົ່ງກັບ",
            step4_title: "ໂຮງແຮມຄູ່ຮ່ວມທຸລະກິດ",
            step4_desc: "ໂຮງແຮມຄູ່ຮ່ວມທຸລະກິດຮັບຄົນເຈັບຕາມມາດຕະຖານການດູແລທີ່ຕົກລົງໄວ້ລ່ວງໜ້າ",
            step5_title: "ການພັກຟື້ນ",
            step5_desc: "ຄົນເຈັບພັກຟື້ນຢ່າງປອດໄພ ພ້ອມນັດຕິດຕາມຜົນກັບຄລີນິກຕົ້ນທາງ",
            services_title: "ບໍລິການໃນລະບົບ",
            services_sub: "ໂມດູນຫຼັກທີ່ WOS ປະສານງານໃຫ້ອັດຕະໂນມັດສຳລັບຄູ່ຮ່ວມທຸລະກິດທຸກຝ່າຍ",
            svc1_title: "Hospital Services",
            svc1_desc: "ຮັບສົ່ງຂໍ້ມູນເຄສຈາກຄລີນິກ/ໂຮງໝໍ ແລະ ຕິດຕາມສະຖານະການປິ່ນປົວແບບຣີໂຕມ",
            svc2_title: "Hotel Network",
            svc2_desc: "ເຄືອຂ່າຍໂຮງແຮມທີ່ຜ່ານມາດຕະຖານການດູແລຄົນເຈັບພັກຟື້ນ ພ້ອມລະບົບຈອງຫ້ອງອັດຕະໂນມັດ",
            svc3_title: "Transportation",
            svc3_desc: "ລົດຮັບສົ່ງ VIP ຈາກສະໜາມບິນ/ດ່ານຊາຍແດນ ກົງສູ່ຄລີນິກ ແລະ ບ່ອນພັກ",
            svc4_title: "Wellness Nutrition",
            svc4_desc: "ເມນູສະເພາະບຸກຄົນຕາມປະເພດການປິ່ນປົວ ຈັດສົ່ງກົງເວລາໂດຍຄູ່ຮ່ວມທຸລະກິດຄົວ",
            ecosystem_title: "WOS ເຊື່ອມທຸກພາກສ່ວນຂອງ Healthcare Hospitality",
            eco_hospital: "ໂຮງໝໍ",
            eco_hotel: "ໂຮງແຮມ",
            eco_wellness: "ສຸຂະພາບລວມ",
            eco_insurance: "ປະກັນໄພ",
            eco_travel: "ການເດີນທາງ",
            ecosystem_cta: "ສະໝັກເປັນຄູ່ຮ່ວມທຸລະກິດຮ່ວມລະບົບ →",
            form_title: "ແບບຟອມປະສານງານສຳລັບຄລີນິກ ແລະ ຄູ່ຮ່ວມທຸລະກິດ",
            form_sub: "ປ້ອນຂໍ້ມູນເຄສເພື່ອສົ່ງເຂົ້າລະບົບ WOS ຫຼືສະໝັກເປັນຄູ່ຮ່ວມທຸລະກິດໂຮງແຮມ/ຄລີນິກ/ນັກລົງທຶນ",
            investor_line: "ນັກລົງທຶນ —",
            investor_link: "ເບິ່ງ Pitch Deck ສະບັບເຕັມ",
            footer_tagline: "Healthcare Hospitality Operating System ເຊື່ອມໂຮງໝໍ ໂຮງແຮມ ແລະ ການເດີນທາງ ເຂົ້າໃນລະບົບດຽວ",
            footer_partner_heading: "Become Partner",
            footer_for_hospital: "ສຳລັບໂຮງໝໍ",
            footer_for_hotel: "ສຳລັບໂຮງແຮມ",
            footer_for_investor: "ສຳລັບນັກລົງທຶນ",
            footer_career: "ຮ່ວມງານກັບພວກເຮົາ",
            footer_system_heading: "ລະບົບ",
            footer_contact_heading: "ຕິດຕໍ່",
            footer_phone: "085-590-7666",
            footer_company_line: "ຫ້າງຫຸ້ນສ່ວນຈຳກັດ Royal Bridge 99 · ເລກທີ 211 ໝູ່ 3 ຖ.ມິດຕະພາບ ຕ.ບ້ານຈັ່ນ ອ.ເມືອງ ອຸດອນທານີ 41000 · ທະບຽນນິຕິບຸກຄົນ: 0413568000586 · ໂທ: 085-590-7666",
            footer_copyright: "© 2026 WOS Platform — Royal Bridge 99 Limited Partnership. ສະຫງວນລິຂະສິດ."
        },
        en: {
            nav_system: "How It Works",
            nav_services: "Services",
            nav_ecosystem: "Ecosystem",
            nav_partner: "For Partners",
            cta_partner_header: "Become a Partner",
            hero_headline: 'The Infrastructure<br>Connecting Hospitals, Hotels, and Transport<br><span class="text-emerald-600">Into One System</span>',
            hero_body: "WOS isn't a recovery-package booking site — it's a coordination system linking clinics, hospitals, hotel networks, transport, and nutrition into a single cross-border care journey between Thailand and Laos.",
            cta_partner: "Join as a System Partner",
            cta_investor: "View Investor Pitch Deck",
            flow_clinic: "Clinic",
            flow_wos: "Operating System",
            flow_hotel: "Hotel",
            flow_transport: "Transport",
            flow_nutrition: "Nutrition",
            flow_journey: "Journey Manager",
            pilot_badge: "Pilot Project — Udon Thani",
            stat_hotels_label: "Partner Hotels",
            stat_clinics_label: "Partner Clinics",
            stat_nights_label: "Recovery Nights Coordinated",
            stat_satisfaction_label: "Guest Satisfaction",
            system_title: "How the System Works",
            system_sub: "WOS is the intermediary that automatically coordinates every party.",
            step1_title: "Clinic Submits Case",
            step1_desc: "The hospital or clinic plans treatment, then submits case details into the WOS system.",
            step2_title: "WOS Processes",
            step2_desc: "The system matches accommodation, transport, and meals suited to the treatment type.",
            step3_title: "Journey Manager",
            step3_desc: "A coordinator tracks the case throughout the journey, from pickup to return.",
            step4_title: "Partner Hotel",
            step4_desc: "The partner hotel receives the patient under pre-agreed care standards.",
            step5_title: "Recovery",
            step5_desc: "The patient recovers safely, with a scheduled follow-up back at the originating clinic.",
            services_title: "Services in the System",
            services_sub: "The core modules WOS automatically coordinates for every partner.",
            svc1_title: "Hospital Services",
            svc1_desc: "Exchange case data with clinics and hospitals, and track treatment status in real time.",
            svc2_title: "Hotel Network",
            svc2_desc: "A network of hotels meeting recovery-care standards, with automated room booking.",
            svc3_title: "Transportation",
            svc3_desc: "VIP transport from the airport or border crossing, direct to the clinic and hotel.",
            svc4_title: "Wellness Nutrition",
            svc4_desc: "Personalized menus by treatment type, delivered on schedule by kitchen partners.",
            ecosystem_title: "WOS Connects Every Part of Healthcare Hospitality",
            eco_hospital: "Hospital",
            eco_hotel: "Hotel",
            eco_wellness: "Wellness",
            eco_insurance: "Insurance",
            eco_travel: "Travel",
            ecosystem_cta: "Join the System as a Partner →",
            form_title: "Coordination Form for Clinics & Partners",
            form_sub: "Submit case details to WOS, or apply as a hotel, clinic, or investor partner.",
            investor_line: "Investors —",
            investor_link: "View the full Pitch Deck",
            footer_tagline: "Healthcare Hospitality Operating System connecting hospitals, hotels, and transport into one system.",
            footer_partner_heading: "Become Partner",
            footer_for_hospital: "For Hospitals",
            footer_for_hotel: "For Hotels",
            footer_for_investor: "For Investors",
            footer_career: "Careers",
            footer_system_heading: "System",
            footer_contact_heading: "Contact",
            footer_phone: "085-590-7666",
            footer_company_line: "Royal Bridge 99 Limited Partnership · 211 Moo 3, Mittraphap Rd., Ban Chan, Mueang, Udon Thani 41000 · Company Reg: 0413568000586 · Tel: 085-590-7666",
            footer_copyright: "© 2026 WOS Platform — Royal Bridge 99 Limited Partnership. All rights reserved."
        }
    };

    const htmlLangMap = { th: "th", lo: "lo", en: "en" };

    function setLang(lang) {
        const dict = translations[lang];
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.dataset.i18n;
            if (dict[key] !== undefined) el.innerHTML = dict[key];
        });
        document.documentElement.lang = htmlLangMap[lang] || 'th';
        document.querySelectorAll('.lang-btn').forEach(btn => {
            btn.classList.toggle('active', btn.dataset.lang === lang);
        });
        try { localStorage.setItem('wos_lang', lang); } catch (e) {}
    }

    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.addEventListener('click', () => setLang(btn.dataset.lang));
    });

    let initialLang = 'th';
    try {
        const saved = localStorage.getItem('wos_lang');
        if (saved && translations[saved]) initialLang = saved;
    } catch (e) {}
    setLang(initialLang);
